server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: authCodeClient
            client-secret: authCodeClient
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            issuer-uri: http://auth-server:9000
#            authorization-uri: http://localhost:9000/oauth2/authorize
#            tokenlimit-uri: http://localhost:9000/oauth2/token
#            user-info-uri: http://localhost:9000/userinfo
#            user-name-attribute: sub
#            user-info-authentication-method: form

logging:
  level:
    org.springframework.security: TRACE
