server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: clientCredClient
            client-secret: clientCredClient
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            scope: openid
        provider:
          spring:
            token-uri: http://auth-server:9000/oauth2/token


logging:
  level:
    org.springframework.security: trace