services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pass -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli","--raw", "incr","ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
      
volumes:
  mysql: