spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: client
          client-secret: secret
          introspection-uri: http://127.0.0.1:8080/oauth2/introspect
server:
  port: 8090
