server:
  port: 8092

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
        opaquetoken:
          introspection-uri: http://localhost:9000/oauth2/introspect
          client-id: introspectClient
          client-secret: introspectClient
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

