server:
  port: 9000

#spring:
#  security:
#    #    user:
#    #      name: user
#    #      password: password
#    oauth2:
#      authorizationserver:
#        client:
#          client-1:
#            registration:
#              client-id: client
#              client-secret: secret
#              client-authentication-methods:
#                - "client_secret_basic"
#                - "client_secret_post"
#              authorization-grant-types:
#                - "client_credentials"
#                - "authorization_code"
#                - "refresh_token"
#              redirect-uris:
#                - "https://oidcdebugger.com/debug"
#                - "https://oauthdebugger.com/debug"
#                - "http://127.0.0.1:8080/login/oauth2/code/spring"
#                - "http://127.0.0.1:8080/authorized"
#              scopes:
#                - "read"
#            require-authorization-consent: true # 需要设置为true，否则 scopes 为空
#            token:
#              access-token-time-to-live: 1d
#              refresh-token-time-to-live: 10d

logging:
  level:
    org.springframework.security: trace