server:
  port: 8070

spring:
  security:
    oauth2:
      client:
        registration:
          messaging-client:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            scope: message.read
            client-name: messaging-client
        provider:
          spring:
            token-uri: http://127.0.0.1:8080/oauth2/token