server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: authCodeClient
            client-secret: authCodeClient
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            issuer-uri: http://localhost:9000


logging:
  level:
    org.springframework.security: TRACE
