spring.security.oauth2.client.registration.spring.provider: spring
spring.security.oauth2.client.registration.spring.client-id: client
spring.security.oauth2.client.registration.spring.client-secret: secret
spring.security.oauth2.client.registration.spring.scope: read
spring.security.oauth2.client.registration.spring.authorization-grant-type: authorization_code
spring.security.oauth2.client.registration.spring.redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
# 如果没有启用 oidc, 则不能使用 issuer-uri, 需要配置 authorization-uri, token-uri, user-info-uri
#spring.security.oauth2.client.provider.spring.issuer-uri: "http://localhost:9000"
spring.security.oauth2.client.provider.spring.authorization-uri: "http://localhost:9000/oauth2/authorize"
spring.security.oauth2.client.provider.spring.token-uri: "http://localhost:9000/oauth2/token"
spring.security.oauth2.client.provider.spring.user-info-uri: "http://localhost:9000/userinfo"
spring.security.oauth2.client.provider.spring.user-name-attribute: "data.sub"
spring.security.oauth2.client.provider.spring.user-info-authentication-method: "form"


logging:
  level:
    org.springframework.security: trace